repos:
- repo: https://github.com/bridgecrewio/checkov.git
  rev: '3.1.69' # change to tag or sha
  hooks:
    - id: checkov
      # - id: checkov_container
      # - id: checkov_diff
      # - id: checkov_diff_container
      # - id: checkov_secrets
      # - id: checkov_secrets_container
